CREATE DATABASE chatlog WITH OWNER = postgres;

DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS MESSAGES CASCADE;

-- Creating tables...
CREATE TABLE IF NOT EXISTS USERS
(
    USERS_ID       VARCHAR(16) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS MESSAGES
(
    MESSAGE_ID        INT PRIMARY KEY
  , MESSAGE_TEXT      VARCHAR(256)
  , TIME_STAMP        TIMESTAMP
  , IS_SENT           BOOL
  , CONSTRAINT FK_USER_ID FOREIGN KEY(USERS_ID) REFERENCES USERS(USERS_ID)
);
